#!/bin/bash

set -x

make realclean
perl Configure.pl --gen-moar --gen-nqp --backends=moar                      &&
perl -pi -e 's/--optimize=\K3/0/' Makefile                                  &&
make                                                                        &&
make test                                                                   &&
make install                                                                &&
cd nqp/MoarVM                                                               &&
git checkout $(git branch -r | grep origin/line_based_coverage | tail -n1)  &&
git pull --rebase https://github.com/MoarVM/MoarVM/                         &&
perl Configure.pl --prefix=../../install/                                   &&
make                                                                        &&
make install                                                                &&
cd ../..                                                                    &&
install/bin/moar --help | grep MVM_COVERAGE_LOG                             &&
    echo 'We SUCCEEDED!!'                                                   ||
    echo 'WE FAILED!!!!'

